In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [ ]:
dbfile = 'data/grand_tours.db'
grand_tour = 'tdf'
year = 2024

conn = sqlite3.connect(dbfile)

query_all = f"SELECT * FROM tdf_results WHERE year = '{year}'"

df = pd.read_sql_query(query_all, conn)

conn.close()

In [11]:
conn = sqlite3.connect(dbfile)

query = f"SELECT * FROM segments_data"

segments_df = pd.read_sql_query(query, conn)

conn.close()

In [5]:
df

,year,stage,name,time,date,start_time,winner_avg_speed,distance,profile_score,vertical_meters,Departure:,Arrival:,startlist_quality,won_how,avg_temperature
0,2024,Stage 1,BARDET Romain,5:07:22,2024-06-29 00:00:00,12:40,40.213,206.0,176.0,3821.0,Firenze,Rimini,1723,Other,30.0
1,2024,Stage 1,VAN DEN BROEK Frank,",,",2024-06-29 00:00:00,12:40,40.213,206.0,176.0,3821.0,Firenze,Rimini,1723,Other,30.0
2,2024,Stage 1,VAN AERT Wout,0:05,2024-06-29 00:00:00,12:40,40.213,206.0,176.0,3821.0,Firenze,Rimini,1723,Other,30.0
3,2024,Stage 1,POGAČAR Tadej,",,",2024-06-29 00:00:00,12:40,40.213,206.0,176.0,3821.0,Firenze,Rimini,1723,Other,30.0
4,2024,Stage 1,VAN GILS Maxim,",,",2024-06-29 00:00:00,12:40,40.213,206.0,176.0,3821.0,Firenze,Rimini,1723,Other,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3427,2024,Stage 21 (ITT),DUJARDIN Sandy,"9.35,22",2024-07-21 00:00:00,14:40,44.521,33.7,73.0,720.0,Monaco,Nice,1723,None,28.0
3428,2024,Stage 21 (ITT),WÆRENSKJOLD Søren,"9.39,38",2024-07-21 00:00:00,14:40,44.521,33.7,73.0,720.0,Monaco,Nice,1723,None,28.0
3429,2024,Stage 21 (ITT),ARNDT Nikias,"9.40,00",2024-07-21 00:00:00,14:40,44.521,33.7,73.0,720.0,Monaco,Nice,1723,None,28.0
3430,2024,Stage 21 (ITT),SOLER Marc,"9.45,79",2024-07-21 00:00:00,14:40,44.521,33.7,73.0,720.0,Monaco,Nice,1723,None,28.0
3431,2024,Stage 21 (ITT),GROENEWEGEN Dylan,"10.40,19",2024-07-21 00:00:00,14:40,44.521,33.7,73.0,720.0,Monaco,Nice,1723,None,28.0

In [4]:
df.dtypes

year                   int64
stage                 object
name                  object
time                  object
date                  object
start_time            object
winner_avg_speed     float64
distance             float64
profile_score        float64
vertical_meters      float64
Departure:            object
Arrival:              object
startlist_quality      int64
won_how               object
avg_temperature      float64
dtype: object

In [8]:
segments_df

,activity_id,athlete_id,date,tour_year,distance,segment
0,50090631,505408,April 22 2013,giro-2013,166.86,"{""segment_name"": [""Rotonda S\u00b4Habitat - Ro..."
1,50269241,110144,April 23 2013,giro-2013,136.07,"{""segment_name"": [""Rilancio dalla piazza"", ""St..."
2,50449480,110144,April 24 2013,giro-2013,140.28,"{""segment_name"": [""Rilancio dalla piazza"", ""St..."
3,50599840,1514397,April 25 2013,giro-2013,37.10,"{""segment_name"": [""Salita dalla Chiesa di Cris..."
4,50847673,505408,April 26 2013,giro-2013,48.97,{}
...,...,...,...,...,...,...
43010,13527881935,9421925,February 3 2025,tdf-2022,86.11,"{""segment_name"": [""Paradores to top"", ""Llano U..."
43011,13528342314,254096,February 3 2025,tdf-2022,132.64,"{""segment_name"": [""Encamp-La Seu"", ""Repecho"", ..."
43012,13528433724,616061,February 3 2025,tdf-2022,207.66,"{""segment_name"": [""San Arenal outclimb"", ""Carr..."
43013,13528459945,6860614,February 3 2025,tdf-2022,208.25,"{""segment_name"": [""San Arenal outclimb"", ""Carr..."
43014,13528593487,12274527,February 3 2025,tdf-2022,209.00,"{""segment_name"": [""San Arenal outclimb"", ""Carr..."

In [9]:
segments_df['segment'][43014]

'{"segment_name": ["San Arenal outclimb", "Carrer Cedre", "CoastRoad Full", "Arenal - Badia Blava", "Subida Ses Palmeras", "ZA 1 min Delta", "Las Palmeras - Sa Torre - Josita", "Sa Torre 2", "Calle Del Cabo Blanco Climb", "RRG_Climb", "Carrer De Santa Catalina, 12 Climb", "\\u00daltimo repecho Sa Torre", "Puig de ros-Talaiots", "recta de Bahias", "Malle - Flach und Schnell", "IAM Cycling TT Test 20min", "Tolleric-Refugi de s\'\\u00c0guila", "SE Lucmajor", "Recta de la Muerte", "SSE Llucmajor cliffs", "Recta Cap Blanc hacia Cas Buso", "La patate d\'Antoine - Stade Fran\\u00e7ais triathlon", "Cap Blanc - Vernisa", "EB 1/5", "Finca Capocorp", "NE Ca\'s Busso", "Along the 6014", "TT FTP", "Sprint", "Cam\\u00ed Vallgornera - Carretera S\\u00b4Estanyol", "ronda a la S\'estanyol", "Baixada a s\'Estanyol", "S\'Estanyol Sprint", "\\ud83c\\uddea\\ud83c\\uddf8 \\ud83d\\udeb4 Sa Rapita W-O.", "S`Estanyol - Sa R\\u00e0pita", "Giles\' Cut and Chase Course", "Avinguda De Miramar, 8 18 Climb", "1er Tram Sortint de Sa R\\u00e0pita", "Port de sa R\\u00e0pita a rotonda", "Cam\\u00ed des Presos MEB", "Ctra.Presos - Llucmajor (Domingueros y Punto)", "Pmv 6015 Climb", "Pmv 6015 Climb", "PMV-6015 Climb", "Avinguda Ramon de Sant Mart\\u00ed Climb", "\\u26fd\\ufe0f\\u27a1\\ufe0fRot.", "Cam\\u00ed De Son Pieres Climb", "\\ud83c\\uddea\\ud83c\\uddf8 \\ud83d\\udeb4 Llucmajor, Ronda de Ponent Z-N.", "Llucmajor - Algaida", "CEDAR SPRINT", "De Llucmajor a cruce Randa", "Subida Son Saleta", "Randa-Algaida", "Randa - Bunyola", "2\\u00aa Subida Carr. Algaida", "Randa-Algaida", "Llegada Algaida", "Sprint Algaida", "Ronda Algaida south to north", "Algaida - Entrada Sta Eug\\u00e8nia", "Algaida-Carretera Sineu", "Algaida-Santa Maria", "pujada entre algaida i sta eugenia", "Carretera sineu-cruce carretera santa Mar\\u00eda", "radar santa eugenia :) o :(", "Sta Eug\\u00e8nia - Sta Maria", "Sprint Sta Eugenia", "Carrer des Molinets", "paso x puente riki", "Pont abans Sta Maria", "Santa Mar\\u00eda - Rotonda Palmanyola", "Santa Mar\\u00eda hasta desv\\u00edo camino", "Ma-13A Climb", "Ma 2020 Climb", "Santa Mar\\u00eda - Rotonda Bunyola", "Sprint rotonda Festival", "Ultimo repecho (Santa Mar\\u00eda - rotonda Bunyola)", "\\ud83c\\uddea\\ud83c\\uddf8 \\ud83d\\udeb4 Cas Binissalamer - Palmanyola (MA2030).", "Santana manda \\u00fanete a su Panda", "Rotonda a vias tren Bunyola", "Carretera De Palma Al Puerto De S\\u00f3ller Climb", "pasado viatren", "Rotonda Palmanyola - Intersecci\\u00f3 de Bunyola", "Rotonda Palmanyola - Rotonda T\\u00fanel S\\u00f3ller", "Rotonda Palmanyola - Coll de Soller top", "Rotonda Bu\\u00f1ola a rotonda Coll de Soller", "cruze bunyola-rotonda", "Coll de S\\u00f3ller", "Coll de S\\u00f3ller - Primeros 3km", "Col Soller first part", "La recta del viento", "Recta1min", "ultimos 3 km soller", "ZA seated climb", "Coll de Soller - Last KM", "Kulgur Attack 6 @ Soller", "Soller sprint", "Kulgur Attack 6 @ Soller", "Soller sprint", "TDM17 Col De Soller Descent", "Coll inder", "Tunnel Descent to Soller Village Roundabout", "SWABES\' CORNER", "DEN BLEDA (Soller) / pirenaica\\u00b7com", "soller-deia", "Final Drill To Villa !", "Strecke Soller-Valdemossa", "pique ramp sprint", "\\u00daltimos 2Km Coll den Bleda", "Ultimo Km Can Bleda", "WWW 167 Above Soller to Past Deia", "Descenso a Llucalcari", "Deia Climb to the village", "Llucalcari - Deia 1km", "CAN COSTA (Dei\\u00e1) / pirenaica\\u00b7com", "Deia Westbound Valledemosa", "Sa Pedrissa", "sa foradada- can costa", "C 710 Climb", "Miramar a Can Costa", "Ultimo km can costa", "Fast descent", "Through Valldemossa", "sprin carretera principal", "valldemossa decent", "Bajada Valldemossa(Record homologado por la UCI)", "quickly Valdemossa out", "Valldemossa \\u2206\\u2193", "Flying home", "fast & furious", "s\\u00b4estret s\\u00b4esgleieta descent", "S\' Esgleieta-Santa Maria", "S\'Esgleieta-Rotonda Palmanyola", "\\ud83c\\udfc1 Segmento B", "\\"S\\" de SON TERMES", "\\ud83c\\uddea\\ud83c\\uddf8 \\ud83d\\udeb4 Palmanyola - Cas Binissalamer (MA2030).", "Rotonda Palmanyola - Rotonda Bunyola", "despasito", "Bunyola Roundabout to Reads Turn off", "Fast to Maria", "Santa Maria Sprint last 2.5km Sheffrec", "Sprint", "Puente de Santa Maria", "Kel\'s viaduct", "Santa Mar\\u00eda - Santa Eug\\u00e9nia", "Viaductje", "Santa Maria.  Algaida", "pm702", "Santa Eugenia sprint Sheffrec", "Recta Sta Eugenia", "MA 3040", "Santa Eugenia 5 min", "Santa Eugeina Kilo sprint", "Carrer ses Monges Climb", "Santa Eugenia to Algaida roundabout", "StaEugeniaToAlgaidaAttack", "1era subida Algaida- Llucmajor", "Algaida->Randa turn", "Algaida - Puig de Randa", "1\\u00ba subida hasta iglesia randa", "CARRETERA ALGAIDA-GR\\u00c0CIA", "Randa", "Small Puig Randa", "First 500 meters of Randa-Cura Climb", "Randa up and down !", "First part after Randa", "pk1 a pk2", "randa 8\\u00b4", "Recta Santuario", "Cura - Recta Sant Honorat", "Randa 2,5 km", "Attack to take photos", "pk3 a pk4", "2\\u00aa PART CURA", "test", "RANDA final FULL GAZZOLINA 95", "Randa Zieleinlauf", "Randa Final", "cura down hill", "Cura - el Arenal", "Randa top to Llucmajor bottom", "Randa descent to main road (Masters stage race)", "DH santuario a randa", "Randa to Llucmajor", "Randa-Viaduct Arenal", "Kulgur Attack 10 near Randa", "PM 501 Randa to Lucmayor downhill", "STG Sprint", "Off the Wagon!", "Llucmajor desvio  son Granada", "Llucmajor - Cami de Sa Torre", "The place where Richie McBride died", "Son Noguera to Arenal along service road", "Un poco de esfuerzo", "Behind the gas station", "Autov\\u00eda De Levante Climb", "Ma-19 Climb", "\\ud83c\\uddea\\ud83c\\uddf8 \\ud83d\\udeb4 Langs de MA-19 (kartbaan) - afdaling.", "\\ud83c\\uddea\\ud83c\\uddf8 \\ud83d\\udeb4 de kartbaan sprint !", "Sprint kartbaan", "Fast", "@CCP Pont de ses Rates", "SPRINT", "Bajada Ca\'n Pere", "Sprint final real", "Carrer Roses Climb", "Upv"], "segment_time": ["1:01", "3:41", "37:11", "9:32", "4:02", "1:18", "4:27", "3:17", "1:09", "2:38", "1:24", "1:16", "11:18", "3:20", "4:00", "18:09", "7:02", "3:41", "1:54", "1:42", "3:21", "5:08", "15:10", "6:09", "1:47", "1:17", "3:59", "7:45", "48s", "4:09", "23:46", "3:26", "1:17", "4:50", "2:53", "8:34", "50s", "2:16", "5:14", "7:04", "12:42", "1:11", "2:28", "1:33", "3:54", "2:37", "46s", "2:06", "19:58", "1:13", "5:07", "2:37", "4:23", "36:55", "43s", "49s", "26s", "14s", "2:03", "11:38", "6:42", "17:05", "56s", "5:50", "35s", "7:24", "37s", "3:00", "46s", "25s", "10:28", "4:06", "40s", "1:01", "4:06", "1:37", "8s", "4:01", "1:01", "2:06", "49s", "24s", "4:14", "7:36", "18:23", "3:17", "1:53", "10:55", "5:59", "1:44", "2:15", "4:50", "6:35", "3:18", "2:10", "57s", "15s", "9:33", "34s", "12:20", "7:24", "2:03", "38s", "11:59", "20:25", "4:57", "39:08", "1:07", "5:51", "2:31", "11:11", "4:04", "4:32", "2:36", "17:24", "8:53", "4:38", "9:46", "3:18", "5:23", "2:11", "53s", "2:30", "45s", "7:06", "3:07", "1:46", "3:45", "18:55", "42s", "3:46", "22:44", "5:27", "10:57", "44s", "5:05", "3:05", "2:15", "6:14", "35s", "8:07", "43s", "23s", "48s", "9:17", "33s", "21:59", "1:57", "5:51", "3:36", "6:44", "3:50", "2:22", "1:11", "9:46", "2:21", "1:46", "7:10", "21:20", "2:30", "6:24", "11:14", "3:29", "1:17", "21:45", "5:38", "2:24", "4:16", "51s", "1:16", "5:52", "42s", "2:02", "3:37", "1:25", "52s", "1:38", "1:00", "11:06", "33:13", "16:03", "3:07", "1:35", "3:12", "18:56", "31s", "1:32", "1:02", "1:52", "10:08", "2:59", "3:11", "11:02", "1:42", "1:25", "45s", "45s", "2:41", "1:16", "47s", "21s", "49s", "1:55", "1:07", "33s", "1:19", "23s"], "segment_speed": ["24.2km/h", "27.4km/h", "44.4km/h", "34.5km/h", "27.7km/h", "27.7km/h", "40.4km/h", "35.3km/h", "31.8km/h", "34.5km/h", "35.7km/h", "33.6km/h", "51.5km/h", "52.9km/h", "53.5km/h", "48.4km/h", "51.6km/h", "50.8km/h", "53.0km/h", "51.3km/h", "45.2km/h", "45.0km/h", "45.9km/h", "43.4km/h", "45.6km/h", "40.3km/h", "47.0km/h", "48.5km/h", "44.6km/h", "49.7km/h", "46.9km/h", "60.1km/h", "61.9km/h", "41.6km/h", "40.1km/h", "43.9km/h", "44.7km/h", "47.1km/h", "44.2km/h", "49.7km/h", "45.6km/h", "45.0km/h", "46.4km/h", "44.3km/h", "40.8km/h", "29.0km/h", "35.6km/h", "29.7km/h", "26.4km/h", "36.8km/h", "33.3km/h", "30.0km/h", "45.0km/h", "43.3km/h", "30.5km/h", "35.9km/h", "52.9km/h", "50.6km/h", "44.6km/h", "44.8km/h", "47.6km/h", "45.6km/h", "39.7km/h", "46.6km/h", "32.1km/h", "45.6km/h", "52.6km/h", "40.4km/h", "44.9km/h", "44.8km/h", "48.8km/h", "50.5km/h", "45.7km/h", "48.7km/h", "54.1km/h", "53.4km/h", "43.6km/h", "47.9km/h", "38.7km/h", "53.0km/h", "51.8km/h", "51.9km/h", "41.8km/h", "41.7km/h", "32.8km/h", "41.3km/h", "41.2km/h", "27.9km/h", "30.1km/h", "26.3km/h", "23.8km/h", "28.7km/h", "27.6km/h", "27.1km/h", "27.8km/h", "29.1km/h", "33.6km/h", "2.9km/h", "14.8km/h", "35.4km/h", "35.5km/h", "59.9km/h", "42.7km/h", "20.7km/h", "26.6km/h", "21.0km/h", "25.9km/h", "20.2km/h", "19.9km/h", "24.7km/h", "35.1km/h", "41.4km/h", "27.6km/h", "27.3km/h", "23.5km/h", "19.1km/h", "17.2km/h", "25.9km/h", "24.5km/h", "27.6km/h", "28.3km/h", "52.4km/h", "26.9km/h", "24.7km/h", "58.6km/h", "64.4km/h", "61.2km/h", "67.9km/h", "42.8km/h", "81.0km/h", "57.5km/h", "30.3km/h", "34.9km/h", "35.6km/h", "29.2km/h", "37.3km/h", "35.8km/h", "42.6km/h", "39.3km/h", "49.2km/h", "18.5km/h", "39.1km/h", "28.5km/h", "36.2km/h", "34.3km/h", "33.4km/h", "33.0km/h", "38.6km/h", "32.9km/h", "34.2km/h", "34.8km/h", "34.2km/h", "35.6km/h", "33.9km/h", "34.9km/h", "30.6km/h", "27.9km/h", "32.1km/h", "27.0km/h", "18.9km/h", "21.1km/h", "25.4km/h", "23.1km/h", "28.6km/h", "25.9km/h", "24.6km/h", "23.9km/h", "27.4km/h", "25.3km/h", "25.6km/h", "26.0km/h", "26.9km/h", "29.2km/h", "26.4km/h", "27.9km/h", "36.0km/h", "22.9km/h", "19.9km/h", "26.9km/h", "39.3km/h", "35.6km/h", "44.9km/h", "44.5km/h", "55.9km/h", "44.5km/h", "48.5km/h", "61.4km/h", "48.6km/h", "30.0km/h", "41.3km/h", "42.9km/h", "40.2km/h", "45.2km/h", "40.8km/h", "33.2km/h", "44.7km/h", "43.5km/h", "53.7km/h", "58.6km/h", "60.5km/h", "63.3km/h", "39.6km/h", "48.1km/h", "53.9km/h", "54.0km/h", "29.6km/h", "22.7km/h"], "watt": ["304W", "227W", "226W", "298W", "304W", "309W", "282W", "333W", "310W", "340W", "375W", "349W", "182W", "148W", "141W", "206W", "178W", "186W", "164W", "231W", "229W", "226W", "219W", "239W", "215W", "298W", "200W", "191W", "245W", "178W", "268W", "169W", "113W", "262W", "250W", "284W", "286W", "264W", "308W", "297W", "348W", "225W", "427W", "364W", "305W", "164W", "169W", "183W", "203W", "309W", "366W", "383W", "221W", "200W", "412W", "378W", "110W", "58W", "167W", "209W", "193W", "202W", "297W", "216W", "403W", "198W", "372W", "208W", "268W", "368W", "218W", "224W", "265W", "231W", "197W", "190W", "456W", "222W", "268W", "189W", "243W", "320W", "334W", "373W", "416W", "432W", "451W", "449W", "435W", "437W", "448W", "440W", "452W", "447W", "483W", "500W", "677W", "34W", "227W", "57W", "58W", "36W", "169W", "319W", "262W", "317W", "282W", "315W", "310W", "318W", "172W", "66W", "292W", "293W", "327W", "353W", "366W", "315W", "312W", "313W", "311W", "102W", "310W", "337W", "153W", "103W", "73W", "146W", "265W", "162W", "194W", "233W", "295W", "284W", "379W", "277W", "274W", "287W", "285W", "275W", "132W", "290W", "377W", "308W", "204W", "321W", "210W", "176W", "204W", "203W", "191W", "201W", "190W", "221W", "226W", "244W", "274W", "240W", "348W", "300W", "392W", "429W", "455W", "449W", "237W", "441W", "455W", "451W", "454W", "430W", "415W", "530W", "484W", "407W", "506W", "533W", "240W", "206W", "41W", "164W", "80W", "73W", "26W", "150W", "227W", "196W", "108W", "218W", "53W", "279W", "249W", "284W", "279W", "293W", "302W", "324W", "299W", "272W", "258W", "236W", "89W", "285W", "172W", "118W", "9W", "30W", "215W"], "heart_rate": ["130bpm", "131bpm", "132bpm", "147bpm", "149bpm", "151bpm", "143bpm", "148bpm", "144bpm", "157bpm", "158bpm", "161bpm", "122bpm", "117bpm", "110bpm", "127bpm", "119bpm", "121bpm", "121bpm", "133bpm", "131bpm", "133bpm", "130bpm", "136bpm", "137bpm", "152bpm", "127bpm", "124bpm", "148bpm", "123bpm", "141bpm", "118bpm", "108bpm", "139bpm", "137bpm", "142bpm", "150bpm", "138bpm", "147bpm", "149bpm", "157bpm", "129bpm", "175bpm", "166bpm", "154bpm", "119bpm", "122bpm", "122bpm", "131bpm", "147bpm", "157bpm", "165bpm", "133bpm", "132bpm", "148bpm", "152bpm", "131bpm", "116bpm", "124bpm", "132bpm", "131bpm", "132bpm", "134bpm", "137bpm", "142bpm", "131bpm", "142bpm", "130bpm", "134bpm", "130bpm", "136bpm", "141bpm", "153bpm", "142bpm", "136bpm", "135bpm", "146bpm", "136bpm", "139bpm", "132bpm", "131bpm", "148bpm", "156bpm", "164bpm", "176bpm", "173bpm", "174bpm", "184bpm", "182bpm", "182bpm", "182bpm", "182bpm", "185bpm", "184bpm", "187bpm", "187bpm", "187bpm", "109bpm", "131bpm", "106bpm", "104bpm", "107bpm", "110bpm", "152bpm", "142bpm", "150bpm", "148bpm", "147bpm", "156bpm", "158bpm", "128bpm", "108bpm", "146bpm", "143bpm", "156bpm", "159bpm", "161bpm", "157bpm", "156bpm", "157bpm", "158bpm", "142bpm", "152bpm", "155bpm", "131bpm", "120bpm", "110bpm", "131bpm", "147bpm", "143bpm", "141bpm", "141bpm", "148bpm", "148bpm", "154bpm", "148bpm", "147bpm", "150bpm", "149bpm", "150bpm", "126bpm", "143bpm", "146bpm", "139bpm", "130bpm", "145bpm", "132bpm", "130bpm", "129bpm", "132bpm", "128bpm", "129bpm", "126bpm", "130bpm", "137bpm", "137bpm", "145bpm", "142bpm", "163bpm", "151bpm", "165bpm", "180bpm", "174bpm", "171bpm", "146bpm", "179bpm", "179bpm", "182bpm", "180bpm", "181bpm", "183bpm", "183bpm", "186bpm", "185bpm", "187bpm", "188bpm", "181bpm", "183bpm", "113bpm", "129bpm", "115bpm", "109bpm", "104bpm", "124bpm", "139bpm", "130bpm", "119bpm", "139bpm", "107bpm", "146bpm", "140bpm", "147bpm", "151bpm", "148bpm", "151bpm", "154bpm", "154bpm", "153bpm", "150bpm", "149bpm", "148bpm", "147bpm", "142bpm", "140bpm", "135bpm", "108bpm", "126bpm"], "segment_distance": ["0.41km", "1.68km", "27.53km", "5.47km", "1.86km", "0.60km", "2.99km", "1.93km", "0.61km", "1.51km", "0.83km", "0.71km", "9.69km", "2.93km", "3.56km", "14.64km", "6.04km", "3.11km", "1.67km", "1.45km", "2.52km", "3.85km", "11.60km", "4.45km", "1.35km", "0.86km", "3.12km", "6.27km", "0.59km", "3.44km", "18.57km", "3.43km", "1.32km", "3.35km", "1.92km", "6.26km", "0.62km", "1.77km", "3.85km", "5.85km", "9.64km", "0.88km", "1.90km", "1.14km", "2.65km", "1.26km", "0.45km", "1.04km", "8.78km", "0.74km", "2.84km", "1.30km", "3.29km", "26.63km", "0.36km", "0.48km", "0.38km", "0.19km", "1.52km", "8.68km", "5.31km", "12.98km", "0.61km", "4.53km", "0.31km", "5.62km", "0.54km", "2.02km", "0.57km", "0.31km", "8.51km", "3.45km", "0.50km", "0.82km", "3.69km", "1.43km", "0.09km", "3.20km", "0.65km", "1.85km", "0.70km", "0.34km", "2.95km", "5.28km", "10.04km", "2.25km", "1.29km", "5.06km", "3.00km", "0.76km", "0.89km", "2.31km", "3.02km", "1.49km", "1.00km", "0.46km", "0.14km", "0.46km", "0.14km", "7.27km", "4.37km", "2.04km", "0.45km", "4.13km", "9.05km", "1.73km", "16.91km", "0.37km", "1.94km", "1.03km", "6.54km", "2.80km", "2.08km", "1.18km", "6.80km", "2.82km", "1.33km", "4.22km", "1.34km", "2.48km", "1.03km", "0.77km", "1.12km", "0.30km", "6.93km", "3.34km", "1.80km", "4.24km", "13.49km", "0.94km", "3.61km", "11.49km", "3.16km", "6.50km", "0.35km", "3.15km", "1.84km", "1.60km", "4.08km", "0.47km", "2.50km", "0.46km", "0.18km", "0.48km", "5.30km", "0.30km", "12.08km", "1.25km", "3.20km", "2.05km", "3.91km", "2.18km", "1.40km", "0.66km", "5.67km", "1.19km", "0.82km", "3.83km", "9.59km", "0.78km", "2.24km", "4.75km", "1.33km", "0.61km", "9.37km", "2.31km", "0.95km", "1.94km", "0.35km", "0.54km", "2.54km", "0.31km", "0.99km", "1.59km", "0.65km", "0.52km", "0.62km", "0.33km", "4.98km", "21.74km", "9.51km", "2.33km", "1.17km", "2.98km", "14.05km", "0.41km", "1.56km", "0.83km", "0.93km", "6.97km", "2.13km", "2.13km", "8.31km", "1.15km", "0.78km", "0.55km", "0.54km", "2.40km", "1.23km", "0.79km", "0.37km", "0.54km", "1.53km", "1.00km", "0.49km", "0.65km", "0.14km"], "segment_vert": ["5m", "33m", "118m", "110m", "61m", "20m", "39m", "50m", "11m", "37m", "27m", "18m", "113m", "28m", "33m", "73m", "40m", "41m", "21m", "28m", "17m", "16m", "26m", "15m", "11m", "21m", "14m", "24m", "5m", "14m", "59m", "51m", "26m", "7m", "2m", "11m", "12m", "6m", "15m", "40m", "62m", "4m", "26m", "13m", "24m", "5m", "4m", "13m", "127m", "11m", "77m", "49m", "49m", "133m", "14m", "11m", "11m", "5m", "22m", "65m", "50m", "47m", "9m", "18m", "8m", "31m", "9m", "10m", "10m", "8m", "20m", "13m", "4m", "7m", "18m", "12m", "3m", "13m", "6m", "10m", "3m", "1m", "43m", "91m", "362m", "63m", "42m", "254m", "147m", "37m", "44m", "115m", "153m", "79m", "50m", "37m", "6m", "37m", "6m", "404m", "235m", "133m", "13m", "233m", "230m", "81m", "387m", "17m", "97m", "71m", "136m", "131m", "57m", "32m", "287m", "171m", "92m", "148m", "90m", "74m", "36m", "51m", "37m", "12m", "291m", "168m", "107m", "218m", "178m", "68m", "107m", "24m", "16m", "25m", "11m", "14m", "10m", "14m", "10m", "7m", "14m", "4m", "9m", "4m", "33m", "6m", "50m", "11m", "18m", "17m", "24m", "16m", "16m", "90m", "46m", "25m", "22m", "47m", "331m", "46m", "144m", "250m", "93m", "38m", "248m", "142m", "59m", "109m", "22m", "30m", "114m", "22m", "46m", "65m", "33m", "24m", "16m", "14m", "243m", "515m", "395m", "135m", "81m", "83m", "170m", "18m", "50m", "11m", "13m", "13m", "14m", "5m", "94m", "3m", "12m", "87m", "3m", "63m", "36m", "24m", "12m", "4m", "34m", "30m", "16m", "14m", "5m"], "segment_grade": ["1.1%", "1.8%", "0.1%", "2.0%", "3.3%", "3.3%", "1.1%", "2.6%", "1.9%", "2.5%", "2.9%", "2.5%", "-0.6%", "-0.9%", "-0.9%", "-0.4%", "-0.6%", "-0.4%", "-1.3%", "0.1%", "-0.5%", "-0.3%", "-0.1%", "0.1%", "-0.5%", "-2.2%", "-0.4%", "-0.3%", "-0.4%", "-0.2%", "0.0%", "-1.5%", "-2.0%", "0.0%", "0.0%", "0.1%", "1.0%", "-0.1%", "0.3%", "0.6%", "0.6%", "0.0%", "1.4%", "1.1%", "0.9%", "-0.4%", "-0.8%", "1.3%", "0.9%", "1.5%", "2.7%", "3.7%", "-1.1%", "-0.4%", "3.8%", "0.9%", "-2.8%", "-2.5%", "-1.5%", "-0.7%", "-0.9%", "-0.3%", "1.5%", "-0.2%", "2.5%", "-0.1%", "1.6%", "0.5%", "1.7%", "2.4%", "-0.1%", "-0.2%", "0.6%", "0.0%", "-0.2%", "0.2%", "3.3%", "0.0%", "1.0%", "-0.5%", "0.0%", "0.3%", "1.5%", "1.7%", "3.6%", "2.8%", "3.3%", "5.1%", "4.9%", "4.9%", "4.9%", "4.9%", "5.1%", "5.3%", "4.9%", "8.1%", "4.4%", "8.1%", "4.4%", "-5.6%", "-5.4%", "-6.5%", "-2.8%", "5.3%", "1.6%", "4.7%", "2.3%", "4.6%", "5.0%", "5.8%", "-1.7%", "-4.5%", "2.7%", "2.5%", "3.9%", "6.0%", "6.9%", "3.5%", "6.7%", "3.0%", "3.4%", "-6.0%", "3.3%", "3.8%", "-4.2%", "-5.0%", "-6.0%", "-5.1%", "-1.2%", "-7.2%", "-3.0%", "0.2%", "0.4%", "0.3%", "3.0%", "0.2%", "0.5%", "-0.9%", "0.1%", "-1.0%", "-0.2%", "0.8%", "4.6%", "0.2%", "0.2%", "1.6%", "0.4%", "-0.9%", "0.4%", "0.4%", "0.0%", "0.5%", "0.1%", "13.4%", "0.8%", "2.0%", "2.6%", "0.9%", "3.4%", "5.8%", "6.4%", "5.5%", "6.9%", "6.2%", "0.1%", "6.1%", "6.2%", "5.2%", "6.1%", "5.6%", "4.5%", "6.9%", "4.6%", "4.1%", "5.0%", "4.2%", "1.8%", "4.0%", "-4.8%", "-2.4%", "-4.1%", "-5.8%", "-6.9%", "-2.8%", "-1.2%", "4.2%", "-3.2%", "-1.4%", "-1.4%", "-0.1%", "-0.6%", "0.2%", "-1.0%", "0.2%", "1.5%", "15.5%", "-0.5%", "-2.5%", "-2.9%", "-3.1%", "-3.2%", "0.0%", "-2.1%", "-3.0%", "-3.3%", "-1.7%", "3.7%"], "VAM": ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "1181", "", "", "1396", "1478", "", "", "1423", "1394", "", "", "", "", "", "", "", "", "", "", "1166", "", "984", "", "", "991", "", "", "", "", "", "989", "1154", "1197", "911", "1640", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "4543", "", "", "", "", "931", "", "1352", "1335", "1602", "", "", "1512", "", "1536", "", "", "1164", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "6944", "", "", ""

In [12]:
conn = sqlite3.connect(dbfile)

query = f"SELECT * FROM stats_data"

stats_df = pd.read_sql_query(query, conn)

conn.close()

In [14]:
stats_df['stat'][0]

'{"dist": "166.86 km", "move_time": "5:53:43", "elevation": "3,695 m", "avg_max": "Speed 28.3 km/h 81.0 km/h", "elapsed": "6:46:34", "device": "Garmin Edge 800"}'